CREATE TABLE [hr].[DAILY_ATTENDENCE] (
    [GKEY]               INT             IDENTITY (1, 1) NOT NULL,
    [EMPLOYEE_GKEY]      INT             NOT NULL,
    [WORK_SITE]          NVARCHAR (50)   NULL,
    [WORK_DATE]          DATE            NOT NULL,
    [WORK_STATUS]        NVARCHAR (1)    CONSTRAINT [DF__DAILY_ATT__WORK___0D44F85C] DEFAULT ('P') NOT NULL,
    [WORK_HOURS_DAY]     DECIMAL (6, 2)  NULL,
    [FIRST_IN]           DATETIME2 (7)   NULL,
    [LAST_OUT]           DATETIME2 (7)   NULL,
    [PUNCH_COUNT]        INT             CONSTRAINT [DF__DAILY_ATT__PUNCH__0E391C95] DEFAULT ((0)) NOT NULL,
    [LEAVE_REQUEST_GKEY] INT             NULL,
    [NOTES]              NVARCHAR (1000) NULL,
    [TENANT_GKEY]        INT             NULL,
    [CREATED_BY]         NVARCHAR (100)  NULL,
    [CREATED_ON]         DATETIME2 (7)   CONSTRAINT [DF__DAILY_ATT__CREAT__0F2D40CE] DEFAULT (sysutcdatetime()) NOT NULL,
    [MODIFIED_BY]        NVARCHAR (100)  NULL,
    [MODIFIED_ON]        DATETIME2 (7)   NULL,
    CONSTRAINT [PK__DAILY_AT__5F3369A0FBF66F2E] PRIMARY KEY CLUSTERED ([GKEY] ASC),
    CONSTRAINT [UQ__DAILY_AT__73E4C9853E7372D7] UNIQUE NONCLUSTERED ([EMPLOYEE_GKEY] ASC, [WORK_DATE] ASC)
);

