CREATE TABLE [hr].[DEPARTMENT] (
    [GKEY]        INT            IDENTITY (1, 1) NOT NULL,
    [NAME]        NVARCHAR (100) NOT NULL,
    [CODE]        NVARCHAR (20)  NULL,
    [DESCRIPTION] NVARCHAR (400) NULL,
    [IS_ACTIVE]   BIT            DEFAULT ((1)) NOT NULL,
    [CREATED_BY]  NVARCHAR (100) NULL,
    [CREATED_ON]  DATETIME2 (7)  DEFAULT (sysutcdatetime()) NOT NULL,
    [UPDATED_BY]  NVARCHAR (100) NULL,
    [UPDATED_ON]  DATETIME2 (7)  DEFAULT (sysutcdatetime()) NOT NULL,
    PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

