CREATE TABLE [hr].[EMPLOYEE_ADDRESS] (
    [GKEY]          INT            IDENTITY (1, 1) NOT NULL,
    [EMPLOYEE_GKEY] INT            NULL,
    [ADDRESS_LINE1] NVARCHAR (200) NULL,
    [ADDRESS_LINE2] NVARCHAR (200) NULL,
    [ADDRESS_LINE3] NVARCHAR (200) NULL,
    [CITY]          NVARCHAR (50)  NULL,
    [DISTRICT]      NVARCHAR (50)  NULL,
    [STATE]         NVARCHAR (50)  NULL,
    [PINCODE]       NVARCHAR (20)  NULL,
    [COUNTRY]       NVARCHAR (50)  DEFAULT ('India') NOT NULL,
    [IS_PRIMARY]    BIT            DEFAULT ((0)) NOT NULL,
    [CREATED_BY]    NVARCHAR (50)  NULL,
    [CREATED_ON]    DATETIME2 (7)  DEFAULT (sysutcdatetime()) NOT NULL,
    [UPDATED_BY]    NVARCHAR (50)  NULL,
    [UPDATED_ON]    DATETIME2 (7)  DEFAULT (sysutcdatetime()) NOT NULL,
    PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

