CREATE TABLE [hr].[HOLIDAY_CALENDAR] (
    [GKEY]                INT            IDENTITY (1, 1) NOT NULL,
    [HOLIDAY_DATE]        DATETIME2 (7)  NOT NULL,
    [HOLIDAY_NAME]        NVARCHAR (100) NOT NULL,
    [HOLIDAY_DESCRIPTION] NVARCHAR (200) NULL,
    [HOLIDAY_TYPE]        NVARCHAR (50)  CONSTRAINT [DF__HOLIDAY_C__HOLID__1209AD79] DEFAULT ('National') NULL,
    [IS_RECURRING]        BIT            CONSTRAINT [DF__HOLIDAY_C__IS_RE__12FDD1B2] DEFAULT ((0)) NULL,
    [IS_OPTIONAL]         BIT            CONSTRAINT [DF__HOLIDAY_C__IS_OP__13F1F5EB] DEFAULT ((0)) NULL,
    [LOCATION]            NVARCHAR (50)  NULL,
    [IS_ACTIVE]           BIT            CONSTRAINT [DF__HOLIDAY_C__IS_AC__14E61A24] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__HOLIDAY___5F3369A04DA29838] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

