CREATE TABLE [hr].[LEAVE_TYPES] (
    [GKEY]              INT            IDENTITY (1, 1) NOT NULL,
    [CODE]              NVARCHAR (50)  NOT NULL,
    [NAME]              NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]       NVARCHAR (200) NULL,
    [IS_PAID]           BIT            CONSTRAINT [DF__LEAVE_TYP__IS_PA__6AEFE058] DEFAULT ((1)) NULL,
    [IS_CARRY_FORWARD]  BIT            CONSTRAINT [DF__LEAVE_TYP__IS_CA__6BE40491] DEFAULT ((0)) NULL,
    [MAX_CARRY_FORWARD] DECIMAL (5, 2) CONSTRAINT [DF__LEAVE_TYP__MAX_C__6CD828CA] DEFAULT ((0)) NULL,
    [IS_ENCASHABLE]     BIT            CONSTRAINT [DF__LEAVE_TYP__IS_EN__6DCC4D03] DEFAULT ((0)) NULL,
    [MAX_ENCASHMENT]    DECIMAL (5, 2) CONSTRAINT [DF__LEAVE_TYP__MAX_E__6EC0713C] DEFAULT ((0)) NULL,
    [MIN_SERVICE_DAYS]  INT            CONSTRAINT [DF__LEAVE_TYP__MIN_S__6FB49575] DEFAULT ((0)) NULL,
    [MAX_PER_MONTH]     DECIMAL (5, 2) NULL,
    [MAX_PER_YEAR]      DECIMAL (5, 2) NULL,
    [GENDER]            NVARCHAR (50)  NULL,
    [REQUIRES_PROOF]    BIT            CONSTRAINT [DF__LEAVE_TYP__REQUI__70A8B9AE] DEFAULT ((0)) NULL,
    [APPROVAL_LEVELS]   INT            CONSTRAINT [DF__LEAVE_TYP__APPRO__719CDDE7] DEFAULT ((1)) NULL,
    [IS_ACTIVE]         BIT            CONSTRAINT [DF__LEAVE_TYP__IS_AC__72910220] DEFAULT ((1)) NULL,
    CONSTRAINT [PK__LEAVE_TY__5F3369A05A21BA58] PRIMARY KEY CLUSTERED ([GKEY] ASC),
    CONSTRAINT [UQ__LEAVE_TY__AA1D4379C758D9C1] UNIQUE NONCLUSTERED ([CODE] ASC)
);

