/* Rollback drops new source identities. Back up and review populated values first. */
SET XACT_ABORT ON;
SET NOCOUNT ON;

IF EXISTS
(
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.PRODUCT_TRANSACTION')
      AND name = 'UX_PRODUCT_TRANSACTION_GRN_SOURCE_LINE'
)
BEGIN
    DROP INDEX UX_PRODUCT_TRANSACTION_GRN_SOURCE_LINE
        ON dbo.PRODUCT_TRANSACTION;
END;

IF COL_LENGTH('dbo.PRODUCT_TRANSACTION', 'SOURCE_LINE_GKEY') IS NOT NULL
BEGIN
    ALTER TABLE dbo.PRODUCT_TRANSACTION
        DROP COLUMN SOURCE_LINE_GKEY;
END;
