using DevExpress.Data;
using DevExpress.Xpf.Core.ConditionalFormatting.Native;
using DevExpress.Xpf.Editors.Settings;
using DevExpress.Xpf.Grid;
using DevExpress.Xpf.WindowsUI;
using InvEntry.ViewModels;
using System.ComponentModel;
using System.Data;
using System.Runtime.Versioning;
using System.Windows;

namespace InvEntry.Views
{
    public partial class GenericReportView : NavigationPage
    {
        public GenericReportView()
        {
            InitializeComponent();

            this.DataContextChanged += GenericReportView_DataContextChanged;
        }

        private void GenericReportView_DataContextChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            if (e.NewValue is GenericReportViewModel vm)
                vm.PropertyChanged += Vm_PropertyChanged;
        }

        [SupportedOSPlatform("windows")]   //To avoid CA1416
        private void Vm_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(GenericReportViewModel.GenericItems))
            {
                var vm = (GenericReportViewModel)sender;
                BuildDynamicColumns(vm.GenericItems);
            }
        }

        [SupportedOSPlatform("windows")]
        private void btnPrintGrid_ItemClick(object sender, DevExpress.Xpf.Bars.ItemClickEventArgs e)
        {
            // Example: Export to Excel
            var dialog = new Microsoft.Win32.SaveFileDialog
            {
                Filter = "Excel Files (*.xlsx)|*.xlsx",
                FileName = "Report.xlsx"
            };

            if (dialog.ShowDialog() == true)
            {
                gridControl.View.ExportToXlsx(dialog.FileName);
            }
        }

        [SupportedOSPlatform("windows")]   //To avoid CA1416
        private void BuildDynamicColumns(DataTable table)
        {
            gridControl.Columns.Clear();
            if (table == null) return;

            foreach (DataColumn col in table.Columns)
            {
                gridControl.Columns.Add(new GridColumn
                {
                    FieldName = col.ColumnName,
                    Header = col.ColumnName,
                    Visible = true
                });
            }
        }

        [SupportedOSPlatform("windows")]   //To avoid CA1416
        private void gridControl_ItemsSourceChanged(object sender, DevExpress.Xpf.Grid.ItemsSourceChangedEventArgs e)
        {
            ApplyDynamicSummaries();
        }

        [SupportedOSPlatform("windows")]   //To avoid CA1416
        private void ApplyDynamicSummaries()
        {
            gridControl.TotalSummary.Clear();

            var table = (gridControl.ItemsSource as DataView)?.Table;
            if (table == null) return;

            foreach (DataColumn col in table.Columns)
            {
                // Only numeric columns should be totaled
                if (col.DataType == typeof(int) ||
                    col.DataType == typeof(long) ||
                    col.DataType == typeof(decimal) ||
                    col.DataType == typeof(double) ||
                    col.DataType == typeof(float))
                {
                    gridControl.TotalSummary.Add(new GridSummaryItem()
                    {
                        FieldName = col.ColumnName,
                        SummaryType = SummaryItemType.Sum,
                        DisplayFormat = "{0:C2}"
                    });
                }
            }
        }

        private void gridControl_AutoGeneratedColumns(object sender, RoutedEventArgs e)
        {
            var table = (gridControl.ItemsSource as DataView)?.Table;
            if (table == null) return;

            foreach (GridColumn col in gridControl.Columns)
            {
                var dataColumn = table.Columns[col.FieldName];
                if (dataColumn == null) continue;

                // Apply formatting ONLY to numeric columns
                if (dataColumn.DataType == typeof(int) ||
                    dataColumn.DataType == typeof(long) ||
                    dataColumn.DataType == typeof(decimal) ||
                    dataColumn.DataType == typeof(double) ||
                    dataColumn.DataType == typeof(float))
                {
                    col.EditSettings = new TextEditSettings()
                    {
                        MaskType = DevExpress.Xpf.Editors.MaskType.Numeric,
                        Mask = "C2",                     // or "C2" for currency
                        MaskUseAsDisplayFormat = true
                    };
                }
            }
        }

    }
}
