CREATE TABLE [dbo].[ar_invoice_receipts] (
    [gkey]                      INT             NOT NULL,
    [cust_gkey]                 INT             NULL,
    [invoice_gkey]              INT             NULL,
    [invoice_nbr]               NCHAR (10)      NULL,
    [invoice_receivable_amount] DECIMAL (18, 2) NULL,
    [balance_after_adj]         DECIMAL (18, 2) NULL,
    [seq_nbr]                   SMALLINT        NOT NULL,
    [transaction_type]          SMALLINT        NULL,
    [mode_of_receipt]           SMALLINT        NULL,
    [bal_before_adj]            DECIMAL (18, 2) NULL,
    [adjusted_amount]           DECIMAL (18, 2) NULL,
    [internal_voucher_nbr]      NCHAR (10)      NULL,
    [internal_voucher_date]     DATETIME2 (7)   NULL,
    [external_transaction_id]   NVARCHAR (MAX)  NULL,
    [external_transaction_date] DATETIME2 (7)   NULL,
    [bank_name]                 NVARCHAR (50)   NULL,
    [other_reference]           NVARCHAR (50)   NULL,
    [sender_bank_account_nbr]   NVARCHAR (50)   NULL,
    [sender_bank_gkey]          SMALLINT        NULL,
    [sender_bank_branch]        NVARCHAR (50)   NULL,
    [sender_bank_ifsc_code]     NVARCHAR (50)   NULL,
    [company_bank_account_nbr]  NVARCHAR (50)   NULL,
    [status]                    SMALLINT        IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_ar_invoice_receipts] PRIMARY KEY CLUSTERED ([gkey] ASC)
);

