CREATE TABLE [dbo].[METALS] (
    [GKEY]       SMALLINT      NOT NULL,
    [METAL_NAME] VARCHAR (100) NULL,
    CONSTRAINT [METALS_PK] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [METALS_PK_2]
    ON [dbo].[METALS]([GKEY] ASC);

