CREATE TABLE [dbo].[ORG_CONTACT] (
    [GKEY]          INT          NOT NULL,
    [MOBILE_NBR]    VARCHAR (15) NOT NULL,
    [CUST_REF_GKEY] INT          NOT NULL,
    [STATUS]        VARCHAR (10) NULL,
    CONSTRAINT [MOBILE_PK] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);




GO
