CREATE TABLE [dbo].[ORG_ADDRESS] (
    [GKEY]           BIGINT        NOT NULL,
    [ADDRESS_LINE1]  VARCHAR (255) NULL,
    [ADDRESS_LINE2]  VARCHAR (255) NULL,
    [ADDRESS_LINE3]  VARCHAR (255) NULL,
    [CITY]           VARCHAR (255) NULL,
    [DISTRICT]       VARCHAR (255) NULL,
    [STATE]          VARCHAR (255) NULL,
    [COUNTRY]        VARCHAR (255) NULL,
    [TENANT_GKEY]    DECIMAL (19)  NULL,
    [CREATED_BY]     VARCHAR (30)  NULL,
    [CREATED_ON]     DATETIME2 (6) NULL,
    [MODIFIED_BY]    VARCHAR (30)  NULL,
    [MODIFIED_ON]    DATETIME2 (6) NULL,
    [AREA]           VARCHAR (255) NULL,
    [GST_STATE_CODE] VARCHAR (3)   NULL,
    CONSTRAINT [ORG_ADDRESS_PK] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ORG_ADDRESS_PK_2]
    ON [dbo].[ORG_ADDRESS]([GKEY] ASC);

