CREATE TABLE [dbo].[ORG_CONTACT_EMAIL] (
    [GKEY]          INT          NOT NULL,
    [CUST_REF_GKEY] INT          NOT NULL,
    [EMAIL_ID]      VARCHAR (50) NULL,
    [ACTIVE_FLAG]   VARCHAR (1)  NULL,
    [STATUS]        VARCHAR (20) NULL,
    CONSTRAINT [EMAIL_PK] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);




GO
