CREATE TABLE [dbo].[ORG_CONTACT] (
    [GKEY]          BIGINT       NOT NULL,
    [MOBILE_NBR]    VARCHAR (15) NOT NULL,
    [CUST_REF_GKEY] VARCHAR (20) NOT NULL,
    [STATUS]        VARCHAR (10) NULL,
    CONSTRAINT [MOBILE_PK] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [MOBILE_PK_2]
    ON [dbo].[ORG_CONTACT]([GKEY] ASC);

