CREATE TABLE [dbo].[ORG_CUSTOMER] (
    [GKEY]           BIGINT        IDENTITY (15000, 1) NOT NULL,
    [CLIENT_ID]      VARCHAR (255) NULL,
    [CUSTOMER_NAME]  VARCHAR (255) NULL,
    [CUSTOMER_TYPE]  VARCHAR (255) NULL,
    [MOBILE_NBR]     VARCHAR (15)  NULL,
    [GSTIN_NBR]      VARCHAR (15)  NULL,
    [LEDGER_NAME]    VARCHAR (255) NULL,
    [NOTES]          VARCHAR (255) NULL,
    [PAN_NBR]        VARCHAR (10)  NULL,
    [STATUS]         VARCHAR (10)  NULL,
    [CREDIT_AVAILED] VARCHAR (3)   NULL,
    [LOCATION_GKEY]  BIGINT        NULL,
    [DELETE_FLAG]    BIT           NULL,
    [CREATED_BY]     VARCHAR (30)  NULL,
    [CREATED_ON]     DATETIME2 (6) NULL,
    [MODIFIED_BY]    VARCHAR (30)  NULL,
    [MODIFIED_ON]    DATETIME2 (6) NULL,
    [TENANT_GKEY]    BIGINT        NULL,
    [ADDRESS_GKEY]   BIGINT        NULL,
    [CUSTOMER_SINCE] DATETIME      NULL,
    [SALUTATIONS]    VARCHAR (10)  NULL,
    [GST_STATE_CODE] NVARCHAR (5)  NULL,
    CONSTRAINT [ORG_CUSTOMER_PK] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ORG_CUSTOMER_PK_2]
    ON [dbo].[ORG_CUSTOMER]([GKEY] ASC);

