CREATE TABLE [dbo].[PRODUCT_GROUP] (
    [GKEY]       INT           NOT NULL,
    [GROUP_NAME] VARCHAR (250) NULL,
    [PURITY]     VARCHAR (20)  NULL,
    [CATEGORY]   VARCHAR (20)  NULL,
    CONSTRAINT [PRODUCT_GROUP_PK] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PRODUCT_GROUP_PK_2]
    ON [dbo].[PRODUCT_GROUP]([GKEY] ASC);

