CREATE TABLE [dbo].[STOCK_TRANSFER_LINE] (
    [GKEY]                  INT             IDENTITY (1, 1) NOT NULL,
    [TRANSFER_HDR_GKEY]     INT             NOT NULL,
    [LINE_NBR]              INT             NOT NULL,
    [PRODUCT_STOCK_GKEY]    INT             NULL,
    [PRODUCT_GKEY]          INT             NULL,
    [PRODUCT_ID]            VARCHAR (50)    NULL,
    [PRODUCT_SKU]           VARCHAR (50)    NULL,
    [PRODUCT_NAME]          VARCHAR (255)   NULL,
    [PRODUCT_CATEGORY]      VARCHAR (255)   NULL,
    [METAL]                 VARCHAR (50)    NULL,
    [PURITY]                VARCHAR (255)   NULL,
    [UOM]                   VARCHAR (50)    NULL,
    [QTY]                   INT             NOT NULL,
    [GROSS_WEIGHT]          DECIMAL (18, 3) NOT NULL,
    [STONE_WEIGHT]          DECIMAL (18, 3) NOT NULL,
    [NET_WEIGHT]            DECIMAL (18, 3) NOT NULL,
    [TRANSACTED_RATE]       DECIMAL (18, 2) NULL,
    [TRANSFER_VALUE]        DECIMAL (18, 2) NULL,
    [NOTES]                 VARCHAR (255)   NULL,
    CONSTRAINT [PK_STOCK_TRANSFER_LINE] PRIMARY KEY CLUSTERED ([GKEY] ASC),
    CONSTRAINT [FK_STOCK_TRANSFER_LINE_HEADER]
        FOREIGN KEY ([TRANSFER_HDR_GKEY]) REFERENCES [dbo].[STOCK_TRANSFER_HEADER] ([GKEY]),
    CONSTRAINT [FK_STOCK_TRANSFER_LINE_PRODUCT_STOCK]
        FOREIGN KEY ([PRODUCT_STOCK_GKEY]) REFERENCES [dbo].[PRODUCT_STOCK] ([GKEY])
);

GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_STOCK_TRANSFER_LINE_HEADER_LINE]
    ON [dbo].[STOCK_TRANSFER_LINE] ([TRANSFER_HDR_GKEY] ASC, [LINE_NBR] ASC);

GO

CREATE NONCLUSTERED INDEX [IX_STOCK_TRANSFER_LINE_PRODUCT_STOCK]
    ON [dbo].[STOCK_TRANSFER_LINE] ([PRODUCT_STOCK_GKEY] ASC);