CREATE TABLE [dbo].[STOCK_TRANSFER_HEADER] (
    [GKEY]                 INT             IDENTITY (1, 1) NOT NULL,
    [TRANSFER_NBR]         VARCHAR (50)    NOT NULL,
    [TRANSFER_DATE]        DATETIME2 (6)   NOT NULL,
    [TRANSFER_TYPE]        VARCHAR (20)    NOT NULL,
    [FROM_BRANCH]          VARCHAR (255)   NOT NULL,
    [FROM_TENANT_GKEY]     INT             NULL,
    [TO_REFERENCE_GKEY]    INT             NOT NULL,
    [TO_REFERENCE_CODE]    VARCHAR (50)    NOT NULL,
    [TO_REFERENCE_VALUE]   VARCHAR (50)    NOT NULL,
    [STATUS]               VARCHAR (20)    NOT NULL,
    [REMARKS]              VARCHAR (255)   NULL,
    [TOTAL_QTY]            INT             NOT NULL,
    [TOTAL_GROSS_WEIGHT]   DECIMAL (18, 3) NOT NULL,
    [TOTAL_STONE_WEIGHT]   DECIMAL (18, 3) NOT NULL,
    [TOTAL_NET_WEIGHT]     DECIMAL (18, 3) NOT NULL,
    [CREATED_BY]           VARCHAR (50)    NULL,
    [CREATED_ON]           DATETIME2 (6)   NOT NULL,
    [MODIFIED_BY]          VARCHAR (50)    NULL,
    [MODIFIED_ON]          DATETIME2 (6)   NULL,
    CONSTRAINT [PK_STOCK_TRANSFER_HEADER] PRIMARY KEY CLUSTERED ([GKEY] ASC),
    CONSTRAINT [FK_STOCK_TRANSFER_HEADER_MTblReferences]
        FOREIGN KEY ([TO_REFERENCE_GKEY]) REFERENCES [dbo].[MTBL_REFERENCES] ([gkey])
);

GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_STOCK_TRANSFER_HEADER_TRANSFER_NBR]
    ON [dbo].[STOCK_TRANSFER_HEADER] ([TRANSFER_NBR] ASC);

GO

CREATE NONCLUSTERED INDEX [IX_STOCK_TRANSFER_HEADER_TRANSFER_DATE]
    ON [dbo].[STOCK_TRANSFER_HEADER] ([TRANSFER_DATE] DESC);

GO

CREATE NONCLUSTERED INDEX [IX_STOCK_TRANSFER_HEADER_STATUS_TYPE_DESTINATION]
    ON [dbo].[STOCK_TRANSFER_HEADER] ([STATUS] ASC, [TRANSFER_TYPE] ASC, [TO_REFERENCE_GKEY] ASC);