
CREATE   VIEW [dbo].[CUSTOMER_ORDER_DB_VIEW] AS
SELECT ORD.CUST_GKEY,
		(SELECT CUSTOMER_NAME
			FROM dbo.ORG_CUSTOMER AS OC
			WHERE OC.GKEY = ORD.CUST_GKEY ) AS CUSTOMER_NAME,
		ORD.CUST_MOBILE_NBR,
		ORD.ORDER_NBR,
		ORD.ORDER_DATE,
		ORD.ORDER_REF_NBR, 
		ORD.ORDER_TYPE,
		ORD.ORDER_DUE_DATE,
		ORD.DELIVERY_DATE,
		ORD.ORDER_STATUS_FLAG,
			   (SELECT REF_VALUE
                       FROM      dbo.MTBL_REFERENCES AS MREF
                       WHERE   (REF_NAME = 'CUST_ORD_STATUS')
					   AND REF_CODE = ORD.ORDER_STATUS_FLAG) AS ORDER_STATUS,
		ORD.ORDER_BRANCH,
		ORD.ADVANCE_PAID_AMOUNT,
		ORD.BALANCE_AMOUNT,
		OL.ORDER_LINE_NBR,
		OL.PROD_CATEGORY,
		OL.PROD_GROSS_WEIGHT,
		OL.PROD_STONE_WEIGHT,
		OL.PROD_NET_WEIGHT,
		OL.PROD_QTY
	 FROM     dbo.CUSTOMER_ORDER AS ORD INNER JOIN
                  dbo.CUSTOMER_ORDER_LINES AS OL ON OL.ORDER_GKEY = ORD.GKEY;
