
CREATE VIEW [dbo].[GRNDBVIEW]
AS
SELECT GH.GRN_NBR				AS	"GRN_NBR",
		GH.GRN_DATE				AS	"GRN_DATE",
		GH.DOCUMENT_TYPE		AS	"DOCUMENT_TYPE",
		GH.ORDER_NBR			AS	"ORDER_NBR",
		GH.ORDER_DATE			AS	"ORDER_DATE",
		GH.SUPPLIER_ID			AS	"SUPPLIER_ID",
		GH.SUPPLIER_REF_NBR		AS	"SUPPLIER_REF_NBR",
		GH.ITEM_RECEIVED_DATE	AS	"ITEM_RECEIVED_DATE",
		GH.GKEY					AS	"GKEY",
		GS.LINE_NBR				AS	"LINE_NBR",
		GS.PRODUCT_GKEY			AS	"PRODUCT_GKEY",
		GS.GROSS_WEIGHT			AS	"GROSS_WEIGHT",
		GS.STONE_WEIGHT			AS	"STONE_WEIGHT",
		GS.NET_WEIGHT			AS	"NET_WEIGHT",
		GS.SUPPLIED_QTY			AS	"SUPPLIED_QTY",		
		GS.PRODUCT_CATEGORY		AS	"PRODUCT_CATEGORY",
		GS.PRODUCT_PURITY		AS	"PRODUCT_PURITY",
		GS.UOM					AS	"UOM"
FROM	GRN_HEADER GH, GRN_LINE_SUMMARY GS
WHERE	GH.GKEY = GS.GRN_HDR_GKEY
