CREATE TABLE [dbo].[CUSTOMER_ORDER] (
    [GKEY]                  INT             IDENTITY (1, 1) NOT NULL,
    [CUST_GKEY]             INT             NULL,
    [CUST_MOBILE_NBR]       VARCHAR (50)    NULL,
    [ORDER_NBR]             VARCHAR (50)    NULL,
    [ORDER_DATE]            DATETIME2 (6)   NULL,
    [ORDER_TYPE]            VARCHAR (50)    NULL,
    [ORDER_DUE_DATE]        DATETIME2 (6)   NULL,
    [DELIVERY_DATE]         DATETIME2 (6)   NULL,
    [ORDER_STATUS_FLAG]     INT             NULL,
    [ORDER_BRANCH]          INT             NULL,
    [SERVICE_BRANCH]        INT             NULL,
    [DELIVERY_BRANCH]       INT             NULL,
    [ORDER_TRANSFER_DATE]   DATETIME2 (6)   NULL,
    [BASE_MATERIAL]         VARCHAR (50)    NULL,
    [TOTAL_GROSS_WEIGHT]    DECIMAL (18, 3) NULL,
    [TOTAL_STONE_WEIGHT]    DECIMAL (18, 3) NULL,
    [TOTAL_NET_WEIGHT]      DECIMAL (18, 3) NULL,
    [ORDERED_ITEMS]         INT             NULL,
    [FULFILLED_ITEMS]       INT             NULL,
    [OLD_METAL_NET_WEIGHT]  DECIMAL (18, 3) NULL,
    [OLD_METAL_FINE_WEIGHT] DECIMAL (18, 3) NULL,
    [BALANCE_WEIGHT]        DECIMAL (18, 3) NULL,
    [METAL_RATE]            DECIMAL (18, 2) NULL,
    [TOTAL_MAKING_CHARGES]  DECIMAL (18, 2) NULL,
    [TOTAL_TAX_AMOUNT]      DECIMAL (18, 2) NULL,
    [TOTAL_ORDER_AMOUNT]    DECIMAL (18, 2) NULL,
    [ADVANCE_PAID_AMOUNT]   DECIMAL (18, 2) NULL,
    [BALANCE_AMOUNT]        DECIMAL (18, 2) NULL,
    [REMARK]                VARCHAR (50)    NULL,
    [CREATED_BY]            VARCHAR (50)    NULL,
    [CREATED_ON]            DATETIME2 (6)   NULL,
    [MODIFIED_BY]           VARCHAR (50)    NULL,
    [MODIFIED_ON]           DATETIME2 (6)   NULL,
    [TENANT_GKEY]           INT             NULL,
    [order_ref_nbr]         VARCHAR (50)    NULL,
    CONSTRAINT [PK_CUSTOMER_ORDER] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

