CREATE TABLE [dbo].[CUSTOMER_ORDER_LINES] (
    [GKEY]                   INT             IDENTITY (1, 1) NOT NULL,
    [ORDER_NBR]              VARCHAR (50)    NULL,
    [ORDER_GKEY]             INT             NULL,
    [ORDER_LINE_NBR]         INT             NULL,
    [PROD_CATEGORY]          VARCHAR (255)   NULL,
    [PRODUCT_GKEY]           INT             NULL,
    [PRODUCT_ID]             VARCHAR (50)    NULL,
    [PRODUCT_SKU]            VARCHAR (50)    NULL,
    [PRODUCT_NAME]           VARCHAR (255)   NULL,
    [PRODUCT_DESC]           VARCHAR (255)   NULL,
    [PRODUCT_METAL]          VARCHAR (50)    NULL,
    [PRODUCT_PURITY]         VARCHAR (255)   NULL,
    [ORDER_SPECIFICATION]    VARCHAR (MAX)   NULL,
    [PROD_QTY]               INT             NOT NULL,
    [PROD_GROSS_WEIGHT]      DECIMAL (18, 3) NULL,
    [PROD_STONE_WEIGHT]      DECIMAL (18, 3) NULL,
    [PROD_NET_WEIGHT]        DECIMAL (18, 3) NULL,
    [ORDER_TYPE]             VARCHAR (50)    NULL,
    [ITEM_NOTES]             VARCHAR (MAX)   NULL,
    [ITEM_PACKED]            BIT             NULL,
    [ORDER_ITEM_DUE_DATE]    DATETIME2 (6)   NULL,
    [DELIVERY_DATE]          DATETIME2 (6)   NULL,
    [ORDER_ITEM_STATUS_FLAG] INT             NULL,
    [ORDER_BRANCH]           INT             NULL,
    [SERVICE_BRANCH]         INT             NULL,
    [DELIVERY_BRANCH]        INT             NULL,
    [ORDER_TRANSFER_DATE]    DATETIME2 (6)   NULL,
    [TOTAL_GROSS_WEIGHT]     DECIMAL (18, 3) NULL,
    [TOTAL_STONE_WEIGHT]     DECIMAL (18, 3) NULL,
    [TOTAL_NET_WEIGHT]       DECIMAL (18, 3) NULL,
    [ORDERED_ITEMS]          INT             NULL,
    [FULFILLED_ITEMS]        INT             NULL,
    [OLD_METAL_NET_WEIGHT]   DECIMAL (18, 3) NULL,
    [OLD_METAL_FINE_PERCENT] DECIMAL (18, 3) NULL,
    [OLD_METAL_FINE_WEIGHT]  DECIMAL (18, 3) NULL,
    [BALANCE_WEIGHT]         DECIMAL (18, 3) NULL,
    [METAL_RATE]             DECIMAL (18, 2) NULL,
    [MAKING_CHARGES]         DECIMAL (18, 2) NULL,
    [VA_PERCENT]             DECIMAL (18, 2) NULL,
    [VA_AMOUNT]              DECIMAL (18, 2) NULL,
    [TAX_AMOUNT]             DECIMAL (18, 2) NULL,
    [ORDER_AMOUNT]           DECIMAL (18, 2) NULL,
    [ADVANCE_PAID_AMOUNT]    DECIMAL (18, 2) NULL,
    [BALANCE_AMOUNT]         DECIMAL (18, 2) NULL,
    [REMARK]                 VARCHAR (50)    NULL,
    [CATALOG_ID]             INT             NULL,
    [DESIGN_NAME]            VARCHAR (MAX)   NULL,
    [PAGE_NBR]               INT             NULL,
    [IMAGE_NAME]             VARCHAR (MAX)   NULL,
    [IMAGE_PATH]             VARCHAR (MAX)   NULL,
    [CREATED_BY]             VARCHAR (50)    NULL,
    [CREATED_ON]             DATETIME2 (6)   NULL,
    [MODIFIED_BY]            VARCHAR (50)    NULL,
    [MODIFIED_ON]            DATETIME2 (6)   NULL,
    [TENANT_GKEY]            INT             NULL,
    CONSTRAINT [PK_CUSTOMER_ORDER_LINES] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

