CREATE TABLE [dbo].[DAILY_STOCK_SUMMARY] (
    [GKey]                       INT             IDENTITY (1, 1) NOT NULL,
    [TRANSACTION_DATE]           DATETIME2 (7)   NULL,
    [METAL]                      VARCHAR (50)    NULL,
    [PRODUCT_CATEGORY]           VARCHAR (50)    NULL,
    [OPENING_STOCK_GROSS_WEIGHT] DECIMAL (18, 3) NULL,
    [OPENING_STOCK_STONE_WEIGHT] DECIMAL (18, 3) NULL,
    [OPENING_STOCK_NET_WEIGHT]   DECIMAL (18, 3) NULL,
    [STOCK_IN_GROSS_WEIGHT]      DECIMAL (18, 3) NULL,
    [STOCK_IN_STONE_WEIGHT]      DECIMAL (18, 3) NULL,
    [STOCK_IN_NET_WEIGHT]        DECIMAL (18, 3) NULL,
    [STOCK_OUT_GROSS_WEIGHT]     DECIMAL (18, 3) NULL,
    [STOCK_OUT_STONE_WEIGHT]     DECIMAL (18, 3) NULL,
    [STOCK_OUT_NET_WEIGHT]       DECIMAL (18, 3) NULL,
    [CLOSING_STOCK_GROSS_WEIGHT] DECIMAL (18, 3) NULL,
    [CLOSING_STOCK_STONE_WEIGHT] DECIMAL (18, 3) NULL,
    [CLOSING_STOCK_NET_WEIGHT]   DECIMAL (18, 3) NULL,
    [OPENING_STOCK_QTY]          INT             NULL,
    [STOCK_IN_QTY]               INT             NULL,
    [STOCK_OUT_QTY]              INT             NULL,
    [CLOSING_STOCK_QTY]          INT             NULL
);

