CREATE TABLE [dbo].[GRN_HEADER] (
    [GKEY]               INT           IDENTITY (1, 1) NOT NULL,
    [GRN_NBR]            VARCHAR (50)  NULL,
    [GRN_DATE]           DATETIME2 (6) NULL,
    [DOCUMENT_TYPE]      VARCHAR (50)  NULL,
    [ORDER_NBR]          VARCHAR (50)  NULL,
    [ORDER_DATE]         DATETIME2 (6) NULL,
    [SUPPLIER_ID]        VARCHAR (50)  NULL,
    [SUPPLIER_REF_NBR]   VARCHAR (150) NULL,
    [CUSTOMER_ORDER_NBR] VARCHAR (50)  NULL,
    [DOCUMENT_REF]       VARCHAR (50)  NULL,
    [DOCUMENT_DATE]      DATETIME2 (6) NULL,
    [CREATED_BY]         VARCHAR (50)  NULL,
    [CREATED_ON]         DATETIME2 (6) NULL,
    [MODIFIED_BY]        VARCHAR (50)  NULL,
    [MODIFIED_ON]        DATETIME2 (6) NULL,
    [STATUS]             VARCHAR (50)  NULL,
    [ITEM_RECEIVED_DATE] DATETIME2 (7) NULL,
    CONSTRAINT [PK_GRN_HEADER] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

