CREATE TABLE [dbo].[GRN_LINE] (
    [GKEY]                 INT             IDENTITY (1, 1) NOT NULL,
    [GRN_HDR_GKEY]         INT             NULL,
    [LINE_NBR]             INT             NULL,
    [product_ID]           VARCHAR (50)    NULL,
    [product_desc]         VARCHAR (50)    NULL,
    [PRODUCT_GKEY]         INT             NOT NULL,
    [PRODUCT_PURITY]       VARCHAR (50)    NULL,
    [supp_product_nbr]     VARCHAR (50)    NULL,
    [supp_product_desc]    VARCHAR (150)   NULL,
    [GROSS_WEIGHT]         DECIMAL (10, 3) NULL,
    [STONE_WEIGHT]         DECIMAL (10, 3) NULL,
    [NET_WEIGHT]           DECIMAL (10, 3) NULL,
    [UOM]                  VARCHAR (50)    NULL,
    [ORDERED_QTY]          INT             NULL,
    [SUPPLIED_QTY]         INT             NULL,
    [RECEIVED_QTY]         INT             NULL,
    [ACCEPTED_QTY]         INT             NULL,
    [REJECTED_QTY]         INT             NULL,
    [RETURNED_QTY]         INT             NULL,
    [STATUS]               VARCHAR (50)    NULL,
    [NOTES]                VARCHAR (250)   NULL,
    [SUPP_VA_PERCENT]      DECIMAL (4, 2)  NULL,
    [SUPP_WASTAGE_PERCENT] DECIMAL (4, 2)  NULL,
    [SUPP_WASTAGE_AMOUNT]  DECIMAL (10, 2) NULL,
    [SUPP_RATE]            DECIMAL (10, 2) NULL,
    [SUPP_MAKING_CHARGES]  DECIMAL (10, 2) NULL,
    [SIZE_ID]              INT             NULL,
    [SIZE]                 VARCHAR (50)    NULL,
    [SIZE_UOM]             VARCHAR (50)    NULL,
    [GRN_LINE_SUMRY_GKEY]  INT             NULL,
    [PRODUCT_SKU]          VARCHAR (50)    NULL,
    CONSTRAINT [PK_GRN_LINE] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

