CREATE TABLE [dbo].[LEDGERS_TRANSACTIONS] (
    [GKEY]               INT             IDENTITY (1, 1) NOT NULL,
    [LEDGER_HDR_GKEY]    INT             NOT NULL,
    [DR_CR]              VARCHAR (25)    NULL,
    [TRANSACTION_DATE]   DATETIME2 (7)   NULL,
    [TRANSACTION_AMOUNT] DECIMAL (18, 2) NULL,
    [STATUS]             BIT             NULL,
    [DOCUMENT_NBR]       VARCHAR (50)    NULL,
    [DOCUMENT_DATE]      DATETIME2 (7)   NULL,
    CONSTRAINT [PK_LEDGERS_TRANSACTIONS] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

