CREATE TABLE [dbo].[PRODUCT_TRANSACTION_SUMMARY] (
    [GKEY]                   INT             IDENTITY (1, 1) NOT NULL,
    [TRANSACTION_DATE]       DATETIME2 (7)   NULL,
    [PRODUCT_SKU]            VARCHAR (50)    NULL,
    [PRODUCT_CATEGORY]       VARCHAR (50)    NULL,
    [OPENING_QTY]            INT             NULL,
    [STOCK_IN_QTY]           INT             NULL,
    [STOCK_OUT_QTY]          INT             NULL,
    [CLOSING_QTY]            INT             NULL,
    [OPENING_GROSS_WEIGHT]   DECIMAL (10, 3) NULL,
    [OPENING_STONE_WEIGHT]   DECIMAL (10, 3) NULL,
    [OPENING_NET_WEIGHT]     DECIMAL (10, 3) NULL,
    [STOCK_IN_GROSS_WEIGHT]  DECIMAL (10, 3) NULL,
    [STOCK_IN_STONE_WEIGHT]  DECIMAL (10, 3) NULL,
    [STOCK_IN_NET_WEIGHT]    DECIMAL (10, 3) NULL,
    [STOCK_OUT_GROSS_WEIGHT] DECIMAL (10, 3) NULL,
    [STOCK_OUT_STONE_WEIGHT] DECIMAL (10, 3) NULL,
    [STOCK_OUT_NET_WEIGHT]   DECIMAL (10, 3) NULL,
    [CLOSING_GROSS_WEIGHT]   DECIMAL (10, 3) NULL,
    [CLOSING_STONE_WEIGHT]   DECIMAL (10, 3) NULL,
    [CLOSING_NET_WEIGHT]     DECIMAL (10, 3) NULL,
    CONSTRAINT [PK_PRODUCT_TRANSACTION_SUMMARY] PRIMARY KEY CLUSTERED ([GKEY] ASC)
);

