CREATE TABLE [dbo].[STOCK_ADJUSTMENT_LINE] (
    [GKEY]                  INT             IDENTITY (1, 1) NOT NULL,
    [ADJUSTMENT_HDR_GKEY]   INT             NOT NULL,
    [LINE_NBR]              INT             NOT NULL,
    [DIRECTION]             VARCHAR (10)    NOT NULL,
    [STOCK_LEVEL]           VARCHAR (20)    NOT NULL,
    [MOVEMENT_KIND]         VARCHAR (20)    NOT NULL,
    [PRODUCT_GKEY]          INT             NOT NULL,
    [PRODUCT_STOCK_GKEY]    INT             NULL,
    [PRODUCT_SKU]           VARCHAR (50)    NULL,
    [PRODUCT_CATEGORY]      VARCHAR (255)   NOT NULL,
    [METAL]                 VARCHAR (50)    NULL,
    [PURITY]                VARCHAR (255)   NULL,
    [UOM]                   VARCHAR (50)    NULL,
    [QTY]                   INT             NOT NULL,
    [GROSS_WEIGHT]          DECIMAL (18, 3) NOT NULL,
    [STONE_WEIGHT]          DECIMAL (18, 3) NOT NULL,
    [NET_WEIGHT]            DECIMAL (18, 3) NOT NULL,
    [PAIR_NBR]              INT             NULL,
    [NOTES]                 VARCHAR (500)   NULL,
    CONSTRAINT [PK_STOCK_ADJUSTMENT_LINE] PRIMARY KEY CLUSTERED ([GKEY] ASC),
    CONSTRAINT [FK_STOCK_ADJUSTMENT_LINE_HEADER]
        FOREIGN KEY ([ADJUSTMENT_HDR_GKEY]) REFERENCES [dbo].[STOCK_ADJUSTMENT_HEADER] ([GKEY]),
    CONSTRAINT [FK_STOCK_ADJUSTMENT_LINE_PRODUCT_STOCK]
        FOREIGN KEY ([PRODUCT_STOCK_GKEY]) REFERENCES [dbo].[PRODUCT_STOCK] ([GKEY]),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_LINE_DIRECTION]
        CHECK ([DIRECTION] IN ('IN', 'OUT')),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_LINE_STOCK_LEVEL]
        CHECK ([STOCK_LEVEL] IN ('CONSOLIDATED', 'SKU')),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_LINE_MOVEMENT_KIND]
        CHECK ([MOVEMENT_KIND] IN ('WEIGHT', 'WHOLE_ITEM')),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_LINE_VALUES]
        CHECK ([QTY] >= 0 AND [GROSS_WEIGHT] >= 0 AND [STONE_WEIGHT] >= 0 AND [NET_WEIGHT] >= 0),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_LINE_SKU_SCOPE]
        CHECK (
            ([STOCK_LEVEL] = 'CONSOLIDATED' AND [PRODUCT_STOCK_GKEY] IS NULL AND [PRODUCT_SKU] IS NULL)
            OR
            ([STOCK_LEVEL] = 'SKU' AND [PRODUCT_STOCK_GKEY] IS NOT NULL AND [PRODUCT_SKU] IS NOT NULL)
        )
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_STOCK_ADJUSTMENT_LINE_HEADER_LINE]
    ON [dbo].[STOCK_ADJUSTMENT_LINE] ([ADJUSTMENT_HDR_GKEY] ASC, [LINE_NBR] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_STOCK_ADJUSTMENT_LINE_PRODUCT]
    ON [dbo].[STOCK_ADJUSTMENT_LINE] ([PRODUCT_GKEY] ASC, [PRODUCT_SKU] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_STOCK_ADJUSTMENT_LINE_PRODUCT_STOCK]
    ON [dbo].[STOCK_ADJUSTMENT_LINE] ([PRODUCT_STOCK_GKEY] ASC)
    WHERE [PRODUCT_STOCK_GKEY] IS NOT NULL;
