CREATE TABLE [dbo].[STOCK_ADJUSTMENT_HEADER] (
    [GKEY]                 INT             IDENTITY (1, 1) NOT NULL,
    [ADJUSTMENT_NBR]       VARCHAR (50)    NOT NULL,
    [ADJUSTMENT_DATE]      DATETIME2 (6)   NOT NULL,
    [ADJUSTMENT_TYPE]      VARCHAR (20)    NOT NULL,
    [REASON_CODE]          VARCHAR (50)    NOT NULL,
    [STATUS]               VARCHAR (20)    NOT NULL,
    [REMARKS]              VARCHAR (500)   NULL,
    [TOTAL_QTY]            INT             NOT NULL,
    [TOTAL_GROSS_WEIGHT]   DECIMAL (18, 3) NOT NULL,
    [TOTAL_STONE_WEIGHT]   DECIMAL (18, 3) NOT NULL,
    [TOTAL_NET_WEIGHT]     DECIMAL (18, 3) NOT NULL,
    [CREATED_BY]           VARCHAR (50)    NULL,
    [CREATED_ON]           DATETIME2 (6)   NOT NULL,
    [MODIFIED_BY]          VARCHAR (50)    NULL,
    [MODIFIED_ON]          DATETIME2 (6)   NULL,
    [FINALISED_ON]         DATETIME2 (6)   NULL,
    CONSTRAINT [PK_STOCK_ADJUSTMENT_HEADER] PRIMARY KEY CLUSTERED ([GKEY] ASC),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_HEADER_TYPE]
        CHECK ([ADJUSTMENT_TYPE] IN ('INCREASE', 'DECREASE', 'REALLOCATION')),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_HEADER_STATUS]
        CHECK ([STATUS] IN ('DRAFT', 'POSTED')),
    CONSTRAINT [CK_STOCK_ADJUSTMENT_HEADER_TOTALS]
        CHECK ([TOTAL_QTY] >= 0 AND [TOTAL_GROSS_WEIGHT] >= 0 AND [TOTAL_STONE_WEIGHT] >= 0 AND [TOTAL_NET_WEIGHT] >= 0)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_STOCK_ADJUSTMENT_HEADER_ADJUSTMENT_NBR]
    ON [dbo].[STOCK_ADJUSTMENT_HEADER] ([ADJUSTMENT_NBR] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_STOCK_ADJUSTMENT_HEADER_DATE]
    ON [dbo].[STOCK_ADJUSTMENT_HEADER] ([ADJUSTMENT_DATE] DESC);
GO

CREATE NONCLUSTERED INDEX [IX_STOCK_ADJUSTMENT_HEADER_STATUS_TYPE]
    ON [dbo].[STOCK_ADJUSTMENT_HEADER] ([STATUS] ASC, [ADJUSTMENT_TYPE] ASC);
