@DataAccess_HostAddress = https://localhost:7001

//GET {{DataAccess_HostAddress}}/weatherforecast/
//Accept: application/json

###
GET {{DataAccess_HostAddress}}/api/address/1525
Accept: application/json

###