using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using DevExpress.Export;
using DevExpress.Mvvm;
using DevExpress.Xpf.Grid;
using DevExpress.XtraGrid;
using DevExpress.XtraPrinting;
using InvEntry.Extension;
using InvEntry.Helpers;
using InvEntry.Models;
using InvEntry.Reports;
using InvEntry.Services;
using InvEntry.Utils.Options;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Threading.Tasks;
using System.Windows;

namespace InvEntry.ViewModels;

public partial class GenericReportViewModel : ObservableObject
{

    [ObservableProperty]
    private string _selectedType;

    [ObservableProperty]
    private DataTable _genericItems;

    [ObservableProperty]
    private DateSearchOption _searchOption;

    [ObservableProperty]
    private DateTime _today = DateTime.Today;

    [ObservableProperty]
    private ObservableCollection<string> _reportNameList;

    public List<string> DataTypes;

    // private readonly IInvoiceService _invoiceService;
    private readonly IRepSalesInvrctDbViewService _repSalesInvrctDbViewService;
    private readonly IReportFactoryService _reportFactoryService;

    public GenericReportViewModel(IRepSalesInvrctDbViewService repSalesInvrctDbViewService,
                                    IReportFactoryService reportFactoryService)
    {
        _repSalesInvrctDbViewService = repSalesInvrctDbViewService;
        _reportFactoryService = reportFactoryService;

        SearchOption = new();
        SearchOption.To = Today.AddDays(-1);
        SearchOption.From = Today.AddDays(-1);

        // Initial load
        PopulateOptions();
        _ = RefreshDataAsync();

        _ = LoadData(SelectedType);

    }

    private void PopulateOptions()
    {
        ReportNameList = new ObservableCollection<string>
            {
                "Invoice", "Receipt", "Product"
            };
    }

    // partial void OnSelectedTypeChanged(string value)

    [RelayCommand]
    private async Task RefreshDataAsync()
    {
        // This partial method is auto-generated by the toolkit
        // It gets called whenever SelectedType changes
        await LoadData("Invoice");
    }

    //
    // Export button wired in XAML: ItemClick="btnPrintGrid_ItemClick"
    private void btnPrintGrid_ItemClick(object sender, DevExpress.Xpf.Bars.ItemClickEventArgs e)
    {

    }
    //

    private async Task LoadData(string type)
    {
        if (type == "Invoice")
        {

            var invoiceReceipts = await _repSalesInvrctDbViewService.GetAll(SearchOption);

            /*            var invoices = new List<InvoiceHeader>
                            {
                                new InvoiceHeader { InvNbr = "INV001", InvDate = DateTime.Now, CustMobile = "ABC Corp", AmountPayable = 1200 },
                                new InvoiceHeader { InvNbr = "INV002", InvDate = DateTime.Now, CustMobile = "XYZ Ltd", AmountPayable = 800 }
                            };*/
            GenericItems = GridDataHelper.MapAndTrim(invoiceReceipts);

        }
        else if (type == "Receipt")
        {
            var receipts = new List<InvoiceArReceipt>
                {
                    new InvoiceArReceipt { InvoiceReceiptNbr = "RC001", InternalVoucherDate = DateTime.Now, BankName = "John", AdjustedAmount = 500 },
                    new InvoiceArReceipt { InvoiceReceiptNbr = "RC002", InternalVoucherDate = DateTime.Now, BankName = "Jane Smith", AdjustedAmount = 750 }
                };
            GenericItems = GridDataHelper.MapAndTrim(receipts);
        }
        else if (type == "Product")
        {
            var products = new List<ProductStock>
                {
                    new ProductStock { ProductSku = "P001", Category = "Laptop", GrossWeight = 65000, SoldQty = 10 },
                    new ProductStock { ProductSku = "P002", Category = "Mouse", GrossWeight = 500, SoldQty = 50 }
                };
            GenericItems = GridDataHelper.MapAndTrim(products);
        }
    }

    [RelayCommand] //CanExecute = nameof(CanPrintStatement))]
    private void StatementPrint()
    {
        //var printed = PrintHelper.Print(_reportFactoryService.CreateFinStatementReport(SearchOption.From, SearchOption.To));

        var report = _reportFactoryService.CreateFinStatementReport((DateTime)SearchOption.From,
                                                (DateTime)SearchOption.To,
                                                SearchOption.Filter1);

        //       PrintHelper.ShowPrintPreviewDialog(Application.Current.MainWindow,report);

        //if (printed.HasValue && printed.Value)
        //    _messageBoxService.ShowMessage("Estimate printed Successfully", "Estimate print", MessageButton.OK, MessageIcon.None);

    }
}

