using CommunityToolkit.Mvvm.ComponentModel;
using Ghostscript.NET.PDFA3Converter.ZUGFeRD;
using InvEntry.Helpers;
using InvEntry.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Runtime.CompilerServices;

namespace InvEntry.ViewModels;

public partial class GenericReportViewModel : ObservableObject
{

    [ObservableProperty]
    private string _selectedType;

    [ObservableProperty]
    private DataTable _genericItems;

    [ObservableProperty]
    private ObservableCollection<string> _reportNameList;

    public List<string> DataTypes;

    public GenericReportViewModel()
    {
        // Initial load
        PopulateOptions();

        LoadData(SelectedType);

    }

    private void PopulateOptions() 
    {
        ReportNameList = new ObservableCollection<string>
            {
                "Invoice", "Receipt", "Product"
            };
    }


    partial void OnSelectedTypeChanged(string value)
    {
        // This partial method is auto-generated by the toolkit
        // It gets called whenever SelectedType changes
        LoadData(value);
    }

    private void LoadData(string type)
    {
        if (type == "Invoice")
        {
            var invoices = new List<InvoiceHeader>
                {
                    new InvoiceHeader { InvNbr = "INV001", InvDate = DateTime.Now, CustMobile = "ABC Corp", AmountPayable = 1200 },
                    new InvoiceHeader { InvNbr = "INV002", InvDate = DateTime.Now, CustMobile = "XYZ Ltd", AmountPayable = 800 }
                };
            GenericItems = GridDataHelper.MapAndTrim(invoices);
        }
        else if (type == "Receipt")
        {
            var receipts = new List<InvoiceArReceipt>
                {
                    new InvoiceArReceipt { InvoiceReceiptNbr = "RC001", InternalVoucherDate = DateTime.Now, BankName = "John", AdjustedAmount = 500 },
                    new InvoiceArReceipt { InvoiceReceiptNbr = "RC002", InternalVoucherDate = DateTime.Now, BankName = "Jane Smith", AdjustedAmount = 750 }
                };
            GenericItems = GridDataHelper.MapAndTrim(receipts);
        }
        else if (type == "Product")
        {
            var products = new List<ProductStock>
                {
                    new ProductStock { ProductSku = "P001", Category = "Laptop", GrossWeight = 65000, SoldQty = 10 },
                    new ProductStock { ProductSku = "P002", Category = "Mouse", GrossWeight = 500, SoldQty = 50 }
                };
            GenericItems = GridDataHelper.MapAndTrim(products);
        }
    }

}


public class GenericRow
{
    public string Col1 { get; set; }
    public string Col2 { get; set; }
    public string Col3 { get; set; }
    public string Col4 { get; set; }
    public string Col5 { get; set; }
    public string Col6 { get; set; }
    public string Col7 { get; set; }
    public string Col8 { get; set; }
    public string Col9 { get; set; }
    public string Col10 { get; set; }
    public string Col11 { get; set; }
    public string Col12 { get; set; }
    public string Col13 { get; set; }
    public string Col14 { get; set; }
    public string Col15 { get; set; }
}
